mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.lmsite.lmfavor.entity
server:
  port: 8077
spring:
  datasource:
    password: rain8240
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/imghub?useUnicode=true&characterEncoding=utf8
