mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.jonnyhub.lmimghub.entity
server:
  port: 8080
spring:
  datasource:
    password: rain8240
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.172.232:3306/imghub?useUnicode=true&useSSL=false&characterEncoding=utf8
